server:
  port: 8080
  servlet:
    context-path: /parking-point

##数据库连接信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parking?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
# 下面为连接池的补充设置，应用到上面所有数据源中
# 初始化大小，最小，最大\
    initialSize: 5
    minIdle: 5
    maxActive: 20
# 配置获取连接等待超时的时间
    maxWait: 60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
  freemarker:
    suffix: .html

# 日志级别配置
logging:
  level:
    root: INFO
    com.parking.point: DEBUG

#实体别名
#mapper文件扫描
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.parking.point.entity

